CREATE TABLE IF NOT EXISTS franchises (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          name VARCHAR(60) UNIQUE NOT NULL
    );

CREATE TABLE IF NOT EXISTS branches (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        franchise_id BIGINT NOT NULL,
                                        name VARCHAR(60) NOT NULL,
    CONSTRAINT fk_branches_franchise
    FOREIGN KEY (franchise_id) REFERENCES franchises(id),
    CONSTRAINT uq_branches_franchise_name
    UNIQUE (franchise_id, name)
    );

CREATE TABLE IF NOT EXISTS products (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        branch_id BIGINT NOT NULL,
                                        name VARCHAR(60) NOT NULL,
    stock INT NOT NULL,
    CONSTRAINT fk_products_branch
    FOREIGN KEY (branch_id) REFERENCES branches(id),
    CONSTRAINT uq_products_branch_name
    UNIQUE (branch_id, name)
    );
